[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "auto-insights"
version = "0.0.1"
description = "Tiny auto EDA/insights helper"
requires-python = ">=3.10"
